"""Reference-STACK consistency core for the cinematic provider.

The single biggest quality lever in the pipeline is *consistency* — the same
face every shot, the same room, the same prop. The old path shipped one flat
portrait per character and let a keyframe edit see a single reference; it drifts
the moment a scene has two people, a recurring location, or a prop that has to
match. This module holds the two pieces that fix that:

  1. **Turnaround SET** (identity, not a portrait). A character is anchored by a
     *set* of consistent views — front (the base), an expression, a
     three-quarter, a profile — not one image. The base view is a text-to-image
     generation; every other view is an *edit from the base* through the same
     consistency model, so they are provably the SAME person. Multiple angles is
     the largest identity-stability gain available (research: visual
     discontinuity drives ~92% of drop-off).
  2. **Reference STACK.** Every keyframe is generated by a multi-reference edit
     fed a *stack* — each shot character's best views + the locked location
     reference + recurring prop references (+ an optional style anchor) — capped
     at the model's reference budget. One call, one frame, every anchor honored.

Everything here is either pure string/list assembly (unit-testable, no I/O) or
a thin render helper that takes an injected client (faked in tests, exactly like
the provider). Network transport lives in :class:`~dramapy.fal_client.FalClient`
and is never exercised by CI.

Chosen model (verified live 2026-08-09): **Nano Banana Pro**
(``fal-ai/nano-banana-pro`` text-to-image + ``fal-ai/nano-banana-pro/edit``
multi-reference edit). Same Gemini-image engine for base and edit, so a
character's base view and its edited turnaround views share identity; the edit
holds several consistent faces across a reference stack, renders 9:16 at up to
4K, and keeps in-frame text (signage, phone screens) legible.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from dramapy.cinematography import build_portrait_prompt, style_grade
from dramapy.errors import ProviderError
from dramapy.fal_client import first_url
from dramapy.spec import ResolvedCharacter, ResolvedSeries

# Nano Banana Pro's practical reference budget (docs: ~14 refs, up to 5
# consistent faces). The stack is capped here so a crowded scene never exceeds
# the model's limit.
STACK_CAP = 14
DEFAULT_KEYFRAME_RESOLUTION = "2K"  # 1K/2K/4K enum on the nano-banana models


@dataclass(frozen=True)
class TurnaroundView:
    """One view of a character's turnaround set. ``base`` views are generated
    text-to-image (the identity anchor); the rest are edited *from* the base so
    they are the same person."""

    slot: str
    base: bool
    phrase: str


# Order matters: the base (front) view is first, and the expression view is
# second so the reference stack — which takes each character's first-then-second
# view — carries identity (front) *and* an acting reference (expression) before
# it reaches the angle views. 4 views: inside the research 4-6 range, one t2i +
# three edits per character.
TURNAROUND_VIEWS: tuple[TurnaroundView, ...] = (
    TurnaroundView(
        "front",
        True,
        "front view, facing camera directly, neutral expression, "
        "head and shoulders in frame",
    ),
    TurnaroundView(
        "expression",
        False,
        "chest-up, intense emotional expression, eyes to camera",
    ),
    TurnaroundView(
        "three_quarter",
        False,
        "three-quarter view, head and body turned about 45 degrees",
    ),
    TurnaroundView(
        "profile",
        False,
        "full side profile view",
    ),
)

# The edit prompt for a derived turnaround view: hold the person from the base
# reference EXACTLY, only change the camera angle / expression.
_SAME_PERSON = (
    "the exact same person from the reference image, identical face, hair and "
    "wardrobe"
)


def slugify(text: str, *, maxlen: int = 48) -> str:
    """Filesystem-safe slug for a location/prop name (``world/<slug>/``)."""
    slug = re.sub(r"[^a-z0-9]+", "-", (text or "").strip().lower()).strip("-")
    slug = slug[:maxlen].strip("-")
    return slug or "unknown"


# ---------------------------------------------------------------------------
# Prompt assembly (pure).
# ---------------------------------------------------------------------------


def base_view_prompt(character: ResolvedCharacter, series: ResolvedSeries) -> str:
    """The turnaround base (front) view — reuses the neutral reference-portrait
    prompt so the anchor matches the house look."""
    return build_portrait_prompt(character, series)


def turnaround_view_prompt(
    view: TurnaroundView, character: ResolvedCharacter, series: ResolvedSeries
) -> str:
    """Edit prompt for a derived turnaround view (fed the base reference)."""
    parts = [
        f"{_SAME_PERSON}: {character.name}",
        view.phrase,
        "clean neutral studio background, soft even key light",
        style_grade(series),
        "vertical 9:16 composition",
    ]
    return ". ".join(part for part in parts if part)


def location_ref_prompt(location: str, series: ResolvedSeries) -> str:
    """Establishing reference for a location — generated once, reused as the
    world anchor across every shot in that location."""
    parts = [
        f"cinematic establishing reference of {location}",
        "no people, empty set, wide angle showing the full space",
        style_grade(series),
        "vertical 9:16 composition",
    ]
    return ". ".join(part for part in parts if part)


def prop_ref_prompt(prop: str, series: ResolvedSeries) -> str:
    """Reference for a recurring prop — a clean, single-object plate reused so
    the object matches every time it appears."""
    parts = [
        f"product reference photo of {prop}",
        "single object centered, plain neutral background, even light",
        style_grade(series),
        "vertical 9:16 composition",
    ]
    return ". ".join(part for part in parts if part)


# ---------------------------------------------------------------------------
# Stack assembly (pure).
# ---------------------------------------------------------------------------


def assemble_reference_stack(
    character_ref_sets: list[list[str]] | tuple[tuple[str, ...], ...],
    *,
    location_ref: str | None = None,
    prop_refs: tuple[str, ...] | list[str] = (),
    style_ref: str | None = None,
    cap: int = STACK_CAP,
    per_char_extra: int = 1,
) -> list[str]:
    """Assemble a keyframe reference stack from the shot's anchors, in priority
    order, de-duplicated and capped at ``cap``.

    Identity is paramount, so tiers are added in this order and the tail is
    dropped first when the cap is hit:

      1. one primary (front) view per character — every face is represented;
      2. the locked location reference — the world anchor;
      3. one extra view per character (the expression) — acting reference;
      4. recurring prop references;
      5. an optional style / LUT anchor frame.
    """
    sets = [list(refs) for refs in character_ref_sets]
    tiers: list[list[str]] = []
    # 1. primary view per character
    tiers.append([refs[0] for refs in sets if refs])
    # 2. location
    tiers.append([location_ref] if location_ref else [])
    # 3. extra views per character (expression, then angles)
    extra: list[str] = []
    for refs in sets:
        extra.extend(refs[1 : 1 + max(0, per_char_extra)])
    tiers.append(extra)
    # 4. props
    tiers.append([r for r in prop_refs if r])
    # 5. style anchor
    tiers.append([style_ref] if style_ref else [])

    out: list[str] = []
    seen: set[str] = set()
    for tier in tiers:
        for url in tier:
            if url and url not in seen:
                seen.add(url)
                out.append(url)
                if cap > 0 and len(out) >= cap:
                    return out
    return out


# ---------------------------------------------------------------------------
# Payload builders (pure) — one edit/t2i shape per model family.
# ---------------------------------------------------------------------------


def _is_nano(model: str) -> bool:
    return "nano-banana" in model


def _is_seedream(model: str) -> bool:
    return "seedream" in model


def t2i_payload(
    model: str,
    prompt: str,
    *,
    resolution: str = DEFAULT_KEYFRAME_RESOLUTION,
    size: tuple[int, int] = (1080, 1920),
) -> dict:
    """Text-to-image payload for a still, forced to 9:16, per model family."""
    if _is_nano(model):
        return {
            "prompt": prompt,
            "aspect_ratio": "9:16",
            "resolution": resolution,
            "num_images": 1,
            "output_format": "jpeg",
        }
    if _is_seedream(model):
        return {
            "prompt": prompt,
            "image_size": {"width": size[0], "height": size[1]},
            "num_images": 1,
            "enable_safety_checker": True,
        }
    # flux / kontext / anything else: aspect-ratio t2i.
    return {
        "prompt": prompt,
        "aspect_ratio": "9:16",
        "num_images": 1,
        "output_format": "jpeg",
    }


def edit_payload(
    model: str,
    prompt: str,
    image_urls: list[str],
    *,
    resolution: str = DEFAULT_KEYFRAME_RESOLUTION,
    size: tuple[int, int] = (1080, 1920),
) -> dict:
    """Multi-reference edit payload, forced to 9:16, per model family."""
    urls = list(image_urls)
    if _is_nano(model):
        return {
            "prompt": prompt,
            "image_urls": urls,
            "aspect_ratio": "9:16",
            "resolution": resolution,
            "num_images": 1,
            "output_format": "jpeg",
        }
    if _is_seedream(model):
        return {
            "prompt": prompt,
            "image_urls": urls,
            "image_size": {"width": size[0], "height": size[1]},
            "num_images": 1,
            "enable_safety_checker": True,
        }
    # flux-pro/kontext/max/multi and friends: aspect-ratio edit.
    return {
        "prompt": prompt,
        "image_urls": urls,
        "aspect_ratio": "9:16",
        "num_images": 1,
        "output_format": "jpeg",
    }


# ---------------------------------------------------------------------------
# Render helpers (client injected; faked in tests).
# ---------------------------------------------------------------------------


def generate_image_url(client, model: str, payload: dict, *, budget_s: float, label: str) -> str:
    """Run an image model and return the first output url, or raise."""
    result = client.run(model, payload, budget_s=budget_s, label=label)
    url = first_url(result, "images", "image")
    if not url:
        raise ProviderError(
            f"{label}: {model} returned no image url: {str(result)[:300]}"
        )
    return url


def render_turnaround_set(
    client,
    *,
    character: ResolvedCharacter,
    series: ResolvedSeries,
    t2i_model: str,
    edit_model: str,
    budget_s: float,
    out_dir: Path | None = None,
    resolution: str = DEFAULT_KEYFRAME_RESOLUTION,
) -> list[dict]:
    """Generate a character's turnaround SET and return one manifest entry per
    view (``{"slot", "url", "file"}``), front first.

    The front view is text-to-image (the identity anchor); every other view is
    an *edit from the front url* so the whole set is the same person. When
    ``out_dir`` is given the pixels are cached alongside the manifest as
    ``ref_<slot>.jpg`` (best-effort; a failed debug download never fails the
    render — the url is what the stack actually reuses)."""
    if out_dir is not None:
        out_dir.mkdir(parents=True, exist_ok=True)

    def _cache(url: str, slot: str) -> str:
        filename = f"ref_{slot}.jpg"
        if out_dir is not None:
            try:
                client.download(url, out_dir / filename)
            except ProviderError:
                pass
        return filename

    views: list[dict] = []
    base_url: str | None = None
    for view in TURNAROUND_VIEWS:
        if view.base:
            prompt = base_view_prompt(character, series)
            payload = t2i_payload(t2i_model, prompt, resolution=resolution)
            url = generate_image_url(
                client, t2i_model, payload,
                budget_s=budget_s, label=f"refset {character.id} {view.slot}",
            )
            base_url = url
        else:
            if base_url is None:  # pragma: no cover — front is always first
                continue
            prompt = turnaround_view_prompt(view, character, series)
            payload = edit_payload(edit_model, prompt, [base_url], resolution=resolution)
            url = generate_image_url(
                client, edit_model, payload,
                budget_s=budget_s, label=f"refset {character.id} {view.slot}",
            )
        views.append({"slot": view.slot, "url": url, "file": _cache(url, view.slot)})
    return views


def render_location_ref(
    client,
    *,
    location: str,
    series: ResolvedSeries,
    t2i_model: str,
    budget_s: float,
    out_path: Path | None = None,
    resolution: str = DEFAULT_KEYFRAME_RESOLUTION,
) -> str:
    """Generate a location's world-anchor reference (text-to-image)."""
    payload = t2i_payload(t2i_model, location_ref_prompt(location, series), resolution=resolution)
    url = generate_image_url(
        client, t2i_model, payload, budget_s=budget_s, label=f"location {slugify(location)}"
    )
    if out_path is not None:
        try:
            client.download(url, out_path)
        except ProviderError:
            pass
    return url


def render_prop_ref(
    client,
    *,
    prop: str,
    series: ResolvedSeries,
    t2i_model: str,
    budget_s: float,
    out_path: Path | None = None,
    resolution: str = DEFAULT_KEYFRAME_RESOLUTION,
) -> str:
    """Generate a recurring prop's reference plate (text-to-image)."""
    payload = t2i_payload(t2i_model, prop_ref_prompt(prop, series), resolution=resolution)
    url = generate_image_url(
        client, t2i_model, payload, budget_s=budget_s, label=f"prop {slugify(prop)}"
    )
    if out_path is not None:
        try:
            client.download(url, out_path)
        except ProviderError:
            pass
    return url
