"""cinematic provider — the frontier quality path: character- AND
world-consistent keyframes via a reference STACK, then frontier
image-to-video.

This is the biggest quality lever in the pipeline. Instead of a single flat
text-to-video call (fal/minimax/dashscope), each shot is rendered in stages,
all through the shared :class:`~dramapy.fal_client.FalClient`:

  1. **Turnaround SETS** (identity, not a portrait). Each character is anchored
     by a *set* of consistent views — front (base) + expression + three-quarter
     + profile — generated the first time we ever render them and cached at
     ``<root>/cast/<char_id>/refset.json`` (+ ``ref_<slot>.jpg`` pixels). The
     front is text-to-image; every other view is an *edit from the front* so the
     set is provably the same person. Multiple angles is the largest
     identity-stability gain available. (A character whose bible already carries
     ``ref_images`` skips generation and uses those.)
  2. **World anchors.** One reference per distinct **location** (from
     ``ctx.location``) and per recurring **prop** (from ``ctx.props``), cached at
     ``<root>/world/<slug>/ref.jpg`` and reused across every shot that shares it
     — the same lock-a-reference trick as cast, extended to sets and objects.
  3. **Reference-STACK keyframe.** A cinematic still generated by a
     multi-reference edit fed a *stack* = each shot character's best views + the
     location ref + the shot's prop refs, capped at the model's reference budget
     and forced to 9:16. One call, one frame, every anchor honored. This
     replaces the old single-reference keyframe.
  4. **Image-to-video.** Kling v2.5 turbo/pro animates the keyframe; the clip
     inherits the keyframe's 9:16 frame. Duration is clamped to ``{5, 10}`` s.
  5. **Post-processing ceiling** (:mod:`dramapy.postprocess`, chained on fal
     urls before the single download): dialogue shots are lip-synced to the SAME
     ElevenLabs line assembly will play; every shot is upscaled. Both are
     best-effort and never fail the shot. Lip-sync is pixels-only — stitch drops
     each clip's audio and rebuilds the track at assembly.

All generation/caching is guarded by a per-key lock held on the provider
instance, so the concurrent shot fan-out never double-generates a character
set, a location, or a prop.

Chosen consistency model (verified live 2026-08-09): **Nano Banana Pro**
(``fal-ai/nano-banana-pro`` t2i + ``fal-ai/nano-banana-pro/edit`` multi-ref
edit) — one Gemini-image engine for base and edit (shared identity), several
consistent faces across a stack, 9:16 at up to 4K, legible in-frame text.
The old single-reference Seedream v4 edit is retained as the graceful fallback.

Env (all optional overrides):
  * ``VIDEO_KEYFRAME_MODEL`` (alias ``VIDEO_CINEMATIC_KEYFRAME_MODEL``; default
    ``fal-ai/nano-banana-pro/edit``) — the reference-stack + turnaround editor.
  * ``VIDEO_CINEMATIC_PORTRAIT_MODEL`` (default ``fal-ai/nano-banana-pro``) —
    the base/anchor text-to-image (turnaround front, world refs, cast-less
    stills).
  * ``VIDEO_CINEMATIC_FALLBACK_KEYFRAME_MODEL`` (default
    ``fal-ai/bytedance/seedream/v4/edit``) — the single-ref fallback keyframe.
  * ``VIDEO_CINEMATIC_I2V_MODEL`` (default
    ``fal-ai/kling-video/v2.5-turbo/pro/image-to-video``).
  * ``VIDEO_KEYFRAME_RESOLUTION`` (``1K``/``2K``/``4K``; default ``2K``).
  * ``VIDEO_REFSTACK_CAP`` (default 14) — the max references per keyframe.
  * ``VIDEO_LIPSYNC`` / ``VIDEO_UPSCALE`` — post-step kill switches (``off``).

Constructing the provider without ``FAL_KEY`` raises :class:`ProviderError`
before any socket opens (via :class:`FalClient`). All failures raise
:class:`ProviderError`; the generator degrades a failed shot to
``render_failed`` and still stitches the survivors.
"""

from __future__ import annotations

import json
import os
import threading
from pathlib import Path

from dramapy import consistency, postprocess, refstack, tiers
from dramapy.cinematography import build_cinematic_prompt
from dramapy.errors import ProviderError
from dramapy.fal_client import FalClient, first_url
from dramapy.providers.base import Provider, ShotContext
from dramapy.voices import (
    ELEVEN_MODEL,
    ELEVEN_SIMILARITY_BOOST,
    _eleven_stability,
    _eleven_text,
    voice_for_tag_elevenlabs,
)

# Nano Banana Pro: one engine, base (t2i) + edit (multi-ref), verified live
# 2026-08-09. The old Seedream v4 edit is kept only as the single-ref fallback.
DEFAULT_PORTRAIT_MODEL = "fal-ai/nano-banana-pro"
DEFAULT_KEYFRAME_MODEL = "fal-ai/nano-banana-pro/edit"
DEFAULT_FALLBACK_KEYFRAME_MODEL = "fal-ai/bytedance/seedream/v4/edit"
DEFAULT_I2V_MODEL = "fal-ai/kling-video/v2.5-turbo/pro/image-to-video"
# Per-fal-call budget. 4K multi-character keyframes + i2v run many minutes and
# fal queue time counts against it; 600s timed out the complex shots. Generous
# default, env-overridable (VIDEO_FAL_BUDGET_S). Matches fal_client's default.
DEFAULT_BUDGET_S = float(os.environ.get("VIDEO_FAL_BUDGET_S") or 1800.0)

# Portrait 9:16; the i2v clip inherits this frame. Nano Banana takes an
# aspect_ratio + resolution tier rather than exact pixels, so this size is the
# fallback (Seedream) frame and the nominal size the payload builder reports.
KEYFRAME_WIDTH = 1080
KEYFRAME_HEIGHT = 1920
_I2V_NEGATIVE = "blur, distort, low quality, warped face, extra limbs, text"


def _clamp_kling_duration(duration_s: float) -> str:
    """Kling i2v accepts only the string enum ``"5"`` / ``"10"`` seconds."""
    return "5" if duration_s < 7.5 else "10"


def _env(*names: str) -> str:
    """First non-empty value among ``names`` (env var lookup)."""
    for name in names:
        value = os.environ.get(name, "").strip()
        if value:
            return value
    return ""


class CinematicProvider(Provider):
    name = "cinematic"
    model = "kling-2.5-turbo-pro"

    def __init__(self) -> None:
        # Raises ProviderError before any socket opens when FAL_KEY is unset.
        self._client = FalClient()
        self._portrait_model = _env("VIDEO_CINEMATIC_PORTRAIT_MODEL") or DEFAULT_PORTRAIT_MODEL
        self._keyframe_model = (
            _env("VIDEO_KEYFRAME_MODEL", "VIDEO_CINEMATIC_KEYFRAME_MODEL")
            or DEFAULT_KEYFRAME_MODEL
        )
        self._fallback_keyframe_model = (
            _env("VIDEO_CINEMATIC_FALLBACK_KEYFRAME_MODEL") or DEFAULT_FALLBACK_KEYFRAME_MODEL
        )
        self._i2v_model = _env("VIDEO_CINEMATIC_I2V_MODEL") or DEFAULT_I2V_MODEL
        self._resolution = _env("VIDEO_KEYFRAME_RESOLUTION") or refstack.DEFAULT_KEYFRAME_RESOLUTION
        try:
            self._stack_cap = int(_env("VIDEO_REFSTACK_CAP") or refstack.STACK_CAP)
        except ValueError:
            self._stack_cap = refstack.STACK_CAP
        # Pre-i2v consistency gate (OFF unless VIDEO_CONSISTENCY_GATE is set):
        # verify every cast member is in the keyframe before spending on i2v,
        # re-rolling the (cheap) keyframe up to N times. ``None`` → no gate.
        self._consistency = consistency.make_checker(self._client)
        try:
            self._gate_rerolls = max(0, int(_env("VIDEO_CONSISTENCY_MAX_REROLLS") or 2))
        except ValueError:
            self._gate_rerolls = 2
        # Render tier (draft|standard|premiere, $VIDEO_TIER). Draft skips the
        # finishing ceiling so the aha-trailer path is cheap/fast (see dramapy.tiers).
        self._tier = tiers.resolve_tier()
        # Per-key locks live on the instance (one provider is shared across the
        # shot thread pool). ``_locks_guard`` protects the registry itself; each
        # key lock serializes that anchor's cache check-then-generate so two
        # concurrent shots never double-generate a character set, location, or
        # prop. Keys: ``char:<id>`` / ``loc:<slug>`` / ``prop:<slug>``.
        self._locks_guard = threading.Lock()
        self._locks: dict[str, threading.Lock] = {}

    # -- locking -------------------------------------------------------------

    def _lock(self, key: str) -> threading.Lock:
        with self._locks_guard:
            lock = self._locks.get(key)
            if lock is None:
                lock = threading.Lock()
                self._locks[key] = lock
            return lock

    # -- reference caches (consistency core) ---------------------------------

    @staticmethod
    def _read_json(path: Path) -> dict | None:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None
        return data if isinstance(data, dict) else None

    def _supplied_refs(self, character, project_root: Path) -> list[str]:
        """Resolve any ``ref_images`` already pinned on the character to
        fal-usable references (http urls pass through; local project paths are
        inlined as data URIs). Empty when the bible has none."""
        out: list[str] = []
        for ref in character.ref_images:
            ref = str(ref)
            if ref.startswith("http://") or ref.startswith("https://") or ref.startswith("data:"):
                out.append(ref)
                continue
            path = Path(ref)
            if not path.is_absolute():
                path = project_root / ref
            if path.is_file():
                try:
                    out.append(self._client.data_uri(path))
                except Exception:
                    continue
        return out

    def _ensure_character_refset(
        self, character, project_root: Path, series, budget: float
    ) -> list[str]:
        """Return the ordered reference-view urls for a character (front first),
        generating + caching the turnaround SET on first use. The whole
        check-then-generate runs under the character's lock (thread-safe against
        the concurrent shot fan-out)."""
        ref_dir = project_root / "cast" / character.id
        manifest = ref_dir / "refset.json"
        with self._lock(f"char:{character.id}"):
            supplied = self._supplied_refs(character, project_root)
            if supplied:
                return supplied
            cached = self._read_json(manifest)
            if cached and isinstance(cached.get("views"), list):
                urls = [v.get("url") for v in cached["views"] if isinstance(v, dict) and v.get("url")]
                if urls:
                    return [str(u) for u in urls]
            views = refstack.render_turnaround_set(
                self._client,
                character=character,
                series=series,
                t2i_model=self._portrait_model,
                edit_model=self._keyframe_model,
                budget_s=budget,
                out_dir=ref_dir,
                resolution=self._resolution,
            )
            ref_dir.mkdir(parents=True, exist_ok=True)
            manifest.write_text(
                json.dumps(
                    {
                        "t2i_model": self._portrait_model,
                        "edit_model": self._keyframe_model,
                        "views": views,
                    }
                ),
                encoding="utf-8",
            )
            return [v["url"] for v in views]

    def _ensure_world_ref(
        self, kind: str, name: str, project_root: Path, series, budget: float
    ) -> str:
        """Return the world-anchor url for a location (``kind="loc"``) or prop
        (``kind="prop"``), generating + caching it once per distinct slug under
        ``<root>/world/<slug>/`` (thread-safe)."""
        slug = f"{kind}-{refstack.slugify(name)}"
        ref_dir = project_root / "world" / slug
        ref_json = ref_dir / "ref.json"
        ref_jpg = ref_dir / "ref.jpg"
        with self._lock(f"{kind}:{slug}"):
            cached = self._read_json(ref_json)
            if cached and cached.get("url"):
                return str(cached["url"])
            if kind == "loc":
                url = refstack.render_location_ref(
                    self._client, location=name, series=series,
                    t2i_model=self._portrait_model, budget_s=budget,
                    out_path=ref_jpg, resolution=self._resolution,
                )
            else:
                url = refstack.render_prop_ref(
                    self._client, prop=name, series=series,
                    t2i_model=self._portrait_model, budget_s=budget,
                    out_path=ref_jpg, resolution=self._resolution,
                )
            ref_dir.mkdir(parents=True, exist_ok=True)
            ref_json.write_text(json.dumps({"url": url, "name": name}), encoding="utf-8")
            return url

    # -- keyframe (reference stack) ------------------------------------------

    def _build_keyframe(self, ctx: ShotContext, stack: list[str], budget: float) -> str:
        """Reference-stack keyframe with graceful degradation:
        nano-banana-pro edit(stack) → single-ref Seedream edit → t2i still."""
        shot = ctx.shot
        prompt = build_cinematic_prompt(ctx, stage="keyframe")
        if stack:
            payload = refstack.edit_payload(
                self._keyframe_model, prompt, stack,
                resolution=self._resolution, size=(KEYFRAME_WIDTH, KEYFRAME_HEIGHT),
            )
            try:
                return refstack.generate_image_url(
                    self._client, self._keyframe_model, payload,
                    budget_s=budget, label=f"keyframe {shot.id}",
                )
            except ProviderError:
                # Fallback: the OLD single-reference edit path (Seedream v4),
                # fed just the primary reference.
                fb = refstack.edit_payload(
                    self._fallback_keyframe_model, prompt, stack[:1],
                    resolution=self._resolution, size=(KEYFRAME_WIDTH, KEYFRAME_HEIGHT),
                )
                try:
                    return refstack.generate_image_url(
                        self._client, self._fallback_keyframe_model, fb,
                        budget_s=budget, label=f"keyframe-fallback {shot.id}",
                    )
                except ProviderError:
                    pass  # fall through to a plain t2i still
        # No references (establish/insert), or every edit failed: t2i still.
        t2i = refstack.t2i_payload(
            self._portrait_model, prompt,
            resolution=self._resolution, size=(KEYFRAME_WIDTH, KEYFRAME_HEIGHT),
        )
        return refstack.generate_image_url(
            self._client, self._portrait_model, t2i,
            budget_s=budget, label=f"keyframe-t2i {shot.id}",
        )

    def _keyframe_with_gate(self, ctx: ShotContext, stack: list[str], budget: float) -> str:
        """Build the keyframe, then (if the consistency gate is enabled) verify
        every cast member is present and re-roll the keyframe until they are —
        BEFORE the expensive i2v. No gate configured, or no characters → just the
        keyframe. Fails safe: any checker error proceeds with the current frame."""
        url = self._build_keyframe(ctx, stack, budget)
        checker = self._consistency
        if checker is None or not ctx.characters:
            return url
        for _ in range(self._gate_rerolls):
            try:
                missing = checker.missing_characters(url, ctx.characters, budget_s=budget)
            except Exception:  # pragma: no cover — never block a shot on a flaky check
                return url
            if not missing:
                return url
            # A fresh keyframe generation often includes the dropped character.
            url = self._build_keyframe(ctx, stack, budget)
        return url  # out of re-rolls: proceed (i2v still runs on the best frame)

    # -- image-to-video ------------------------------------------------------

    def _render_video_url(
        self, ctx: ShotContext, keyframe_url: str, budget: float
    ) -> str:
        """Kling i2v -> the clip's fal url. No download: the post chain runs on
        fal urls, and only the final url is downloaded (in ``render_shot``)."""
        shot = ctx.shot
        prompt = build_cinematic_prompt(ctx, stage="motion")
        result = self._client.run(
            self._i2v_model,
            {
                "prompt": prompt,
                "image_url": keyframe_url,
                "duration": _clamp_kling_duration(shot.duration_s),
                "negative_prompt": _I2V_NEGATIVE,
                "cfg_scale": 0.5,
            },
            budget_s=budget,
            label=f"i2v {shot.id}",
        )
        video_url = first_url(result, "video")
        if not video_url:
            raise ProviderError(
                f"cinematic: image-to-video for shot '{shot.id}' returned no "
                f"video url: {json.dumps(result)[:300]}"
            )
        return video_url

    # -- post-processing ceiling (lip-sync + upscale, chained on fal urls) ---

    def _lipsync_audio_url(self, ctx: ShotContext, budget: float) -> str | None:
        """ElevenLabs eleven-v3 audio for the shot's line, cast with the SAME
        voice mapping the assembly stage uses so the lip-synced mouth matches
        the heard voice. Returns the audio fal url, or ``None`` on any failure
        (the caller then keeps the un-synced clip)."""
        shot = ctx.shot
        character = ctx.characters[0]
        voice_name = voice_for_tag_elevenlabs(character.voice)
        emotion = shot.emotion or ""
        result = self._client.run(
            ELEVEN_MODEL,
            {
                "text": _eleven_text(shot.line or "", emotion),
                "voice": voice_name,
                "stability": _eleven_stability(emotion),
                "similarity_boost": ELEVEN_SIMILARITY_BOOST,
            },
            budget_s=budget,
            label=f"lipsync-voice {shot.id}",
        )
        return first_url(result, "audio")

    def _postprocess_url(self, ctx: ShotContext, clip_url: str, budget: float) -> str:
        """Apply the post-processing ceiling to a clip fal url and return the
        final url to download. Every step is best-effort: any failure falls back
        to the previous url so the shot never fails on post-processing."""
        shot = ctx.shot
        # The tier can drop finishing stages — the draft/aha-trailer path trades
        # polish for speed + cost (see dramapy.tiers). A stage runs only if the
        # tier keeps it AND its own env gate is on.
        tier_off = self._tier.stages_off
        # Lip-sync: dialogue shots only. Sync the mouth to the line's ElevenLabs
        # audio (same voice as assembly). Any failure -> keep the un-synced clip.
        if (
            "lipsync" not in tier_off
            and shot.kind == "dialogue"
            and shot.line
            and ctx.characters
            and postprocess.lipsync_enabled()
        ):
            try:
                audio_url = self._lipsync_audio_url(ctx, budget)
                if audio_url:
                    clip_url = postprocess.lipsync(
                        self._client, clip_url, audio_url, budget_s=budget
                    )
            except Exception:
                # Best-effort: fall back to the un-synced clip url.
                pass
        # Upscale: every shot. Any failure -> keep the previous url.
        if "upscale" not in tier_off and postprocess.upscale_enabled():
            try:
                clip_url = postprocess.upscale(self._client, clip_url, budget_s=budget)
            except Exception:
                pass
        return clip_url

    # -- Provider interface --------------------------------------------------

    def render_shot(self, ctx: ShotContext) -> Path:
        budget = ctx.max_render_s or DEFAULT_BUDGET_S
        # output is <root>/episodes/epNNN_shots/shot_*.mp4 -> parents[2] == root
        try:
            project_root = ctx.output_path.parents[2]
        except IndexError as exc:  # pragma: no cover — generator always nests 3 deep
            raise ProviderError(
                f"cinematic: output path {ctx.output_path} is not nested deep "
                "enough to locate the project root (expected "
                "<root>/episodes/<ep>_shots/shot.mp4)"
            ) from exc

        # 1. Character turnaround SETS (cached + thread-safe), ordered per char.
        char_ref_sets = [
            self._ensure_character_refset(character, project_root, ctx.series, budget)
            for character in ctx.characters
        ]
        # 2. World anchors: one reference per distinct location + recurring prop.
        location_ref = (
            self._ensure_world_ref("loc", ctx.location, project_root, ctx.series, budget)
            if ctx.location
            else None
        )
        prop_refs = tuple(
            self._ensure_world_ref("prop", prop, project_root, ctx.series, budget)
            for prop in ctx.props
            if prop
        )
        # 3. Assemble the reference STACK (capped, de-duplicated, prioritized).
        stack = refstack.assemble_reference_stack(
            char_ref_sets,
            location_ref=location_ref,
            prop_refs=prop_refs,
            cap=self._stack_cap,
        )

        # 4. Keyframe (reference-stack edit, 9:16, with graceful fallback) +
        #    the pre-i2v consistency gate (no-op unless enabled).
        keyframe_url = self._keyframe_with_gate(ctx, stack, budget)
        # Debug: keep the keyframe next to the clip (best-effort).
        try:
            self._client.download(
                keyframe_url,
                ctx.output_path.with_name(f"{ctx.output_path.stem}_key.jpg"),
            )
        except ProviderError:
            pass

        # 5. Image-to-video -> the clip's fal url (not yet downloaded).
        clip_url = self._render_video_url(ctx, keyframe_url, budget)

        # 6. Post-processing ceiling: lip-sync (dialogue) + upscale, chained on
        #    fal urls. Only the FINAL url is downloaded.
        final_url = self._postprocess_url(ctx, clip_url, budget)
        # No -an: stitch discards every clip's audio at assembly (concat a=0 +
        # a rebuilt track), so a muxed audio track on the synced clip is inert.
        self._client.download(final_url, ctx.output_path)
        if not ctx.output_path.is_file() or ctx.output_path.stat().st_size == 0:
            raise ProviderError(
                f"cinematic: render for shot '{ctx.shot.id}' produced no clip at "
                f"{ctx.output_path}"
            )
        # Cheap insurance: bake upright if a post step left a rotate flag
        # (no-op for the normal upright clip). Best-effort — never fails a shot.
        try:
            postprocess.normalize_orientation(ctx.output_path)
        except Exception:  # pragma: no cover — normalize is already best-effort
            pass
        return ctx.output_path
